namespace WibboEmulator.Game.Items
{
    public enum InteractionType
    {
        ACTION_BOT_CLOTHES,
        ACTION_BOT_FOLLOW_AVATAR,
        ACTION_BOT_GIVE_HANDITEM,
        ACTION_BOT_MOVE,
        ACTION_BOT_TALK,
        ACTION_BOT_TALK_TO_AVATAR,
        ACTION_BOT_TELEPORT,
        ACTION_CALL_STACKS,
        ACTION_CHASE,
        ACTION_COLLISION_CASE,
        ACTION_COLLISION_TEAM,
        ACTION_ENDGAME_TEAM,
        ACTION_FLEE,
        ACTION_GIVE_REWARD,
        ACTION_GIVE_SCORE,
        ACTION_GIVE_SCORE_TM,
        ACTION_JOIN_TEAM,
        ACTION_KICK_USER,
        ACTION_LEAVE_TEAM,
        ACTION_MOVE_ROTATE,
        ACTION_MOVE_TO_DIR,
        ACTION_POS_RESET,
        ACTION_RESET_TIMER,
        ACTION_SUPER_WIRED,
        ACTION_TELEPORT_TO,
        ACTION_TOGGLE_STATE,
        ACTION_USER_MOVE,
        ACTIONSHOWMESSAGE,
        ADS_BACKGROUND,
        ALERT,
        ARROW,
        BADGE,
        BADGE_DISPLAY,
        BADGE_TROC,
        BADGEBOX,
        BANZAIBLO,
        BANZAIBLOB,
        BANZAIFLOOR,
        BANZAIGATEBLUE,
        BANZAIGATEGREEN,
        BANZAIGATERED,
        BANZAIGATEYELLOW,
        BANZAIPUCK,
        BANZAIPYRAMID,
        BANZAISCOREBLUE,
        BANZAISCOREGREEN,
        BANZAISCORERED,
        BANZAISCOREYELLOW,
        BANZAITELE,
        BED,
        BOT,
        BOTTLE,
        CHRONOTIMER,
        COLORTILE,
        COLORWHEEL,
        CONDITION_ACTOR_IN_GROUP,
        CONDITION_ACTOR_IN_TEAM,
        CONDITION_DATE_RNG_ACTIVE,
        CONDITION_FURNIS_HAVE_NO_USERS,
        CONDITION_FURNIS_HAVE_USERS,
        CONDITION_HAS_FURNI_ON_FURNI,
        CONDITION_HAS_FURNI_ON_FURNI_NEGATIVE,
        CONDITION_HAS_HANDITEM,
        CONDITION_NOT_IN_GROUP,
        CONDITION_NOT_IN_TEAM,
        CONDITION_NOT_STUFF_IS,
        CONDITION_NOT_USER_COUNT,
        CONDITION_STATE_POS,
        CONDITION_STATE_POS_NEGATIVE,
        CONDITION_STUFF_IS,
        CONDITION_SUPER_WIRED,
        CONDITION_TIME_LESS_THAN,
        CONDITION_TIME_MORE_THAN,
        CONDITION_TRIGGER_ON_FURNI,
        CONDITION_TRIGGER_ON_FURNI_NEGATIVE,
        CONDITION_USER_COUNT_IN,
        CRACKABLE,
        CROSSTRAINER,
        DELUXEBOX,
        DICE,
        EXCHANGE,
        EXTRABOX,
        FBGATE,
        FIREGATE,
        FLOOR,
        FLOORSWITCH1,
        FOOTBALL,
        FOOTBALLCOUNTERBLUE,
        FOOTBALLCOUNTERGREEN,
        FOOTBALLCOUNTERRED,
        FOOTBALLCOUNTERYELLOW,
        footballgoalblue,
        FOOTBALLGOALGREEN,
        FOOTBALLGOALRED,
        FOOTBALLGOALYELLOW,
        FREEZEBLUECOUNTER,
        FREEZEBLUEGATE,
        FREEZEEXIT,
        FREEZEGREENCOUNTER,
        FREEZEGREENGATE,
        FREEZEREDCOUNTER,
        FREEZEREDGATE,
        FREEZETILE,
        FREEZETILEBLOCK,
        FREEZEYELLOWCOUNTER,
        FREEZEYELLOWGATE,
        GATE,
        GIFT,
        GLASSFOOR,
        GNOMEBOX,
        GUILD_GATE,
        GUILD_ITEM,
        HABBOWHEEL,
        HALOWEENPOOL,
        HIGHSCORE,
        HIGHSCOREPOINTS,
        HORSE_BODY_DYE,
        HORSE_HAIR_DYE,
        HORSE_HAIRSTYLE,
        HORSE_SADDLE_1,
        HORSE_SADDLE_2,
        ICESKATES,
        JMPHORSE,
        JUKEBOX,
        LANDSCAPE,
        LEGENDBOX,
        LOOTBOX2022,
        LOVELOCK,
        LOVESHUFFLER,
        LOWPOOL,
        MANNEQUIN,
        MONSTERGRAINE,
        MOODLIGHT,
        NONE,
        NORMSLASKATES,
        ONEWAYGATE,
        PET,
        PHOTO,
        PILEMAGIC,
        POOL,
        POSTIT,
        PRESSUREPAD,
        PUZZLEBOX,
        RENTALS,
        RINGPLATE,
        ROLLER,
        ROOMEFFECT,
        SCOREBOARD,
        SPECIALRANDOM,
        SPECIALUNSEEN,
        TELEPORT,
        TONER,
        TRAMPOLINE,
        TREADMILL,
        TRIGGER_AVATAR_ENTERS_ROOM,
        TRIGGER_AVATAR_SAYS_SOMETHING,
        TRIGGER_BOT_REACHED_AVTR,
        TRIGGER_BOT_REACHED_STF,
        TRIGGER_COLLISION,
        TRIGGER_COLLISION_USER,
        TRIGGER_COMMAND,
        TRIGGER_GAME_ENDS,
        TRIGGER_GAME_STARTS,
        TRIGGER_ONCE,
        TRIGGER_PERIODICALLY,
        TRIGGER_PERIODICALLY_LONG,
        TRIGGER_SCORE_ACHIEVED,
        TRIGGER_SELF,
        TRIGGER_STATE_CHANGED,
        TRIGGER_WALK_OFF_FURNI,
        TRIGGER_WALK_ON_FURNI,
        TROPHY,
        TVYOUTUBE,
        VENDINGENABLEMACHINE,
        VENDINGMACHINE,
        WALLPAPER,
        WIRE,
        WIRECENTER,
        WIRECORNER,
        WIRESPLITTER,
        WIRESTANDARD,
    }

    public class InteractionTypes
    {
        public static InteractionType GetTypeFromString(string pType)
        {
            return pType switch
            {
                "default" => InteractionType.NONE,
                "gate" => InteractionType.GATE,
                "photo" => InteractionType.PHOTO,
                "postit" => InteractionType.POSTIT,
                "roomeffect" => InteractionType.ROOMEFFECT,
                "dimmer" => InteractionType.MOODLIGHT,
                "trophy" => InteractionType.TROPHY,
                "bed" => InteractionType.BED,
                "scoreboard" => InteractionType.SCOREBOARD,
                "vendingmachine" => InteractionType.VENDINGMACHINE,
                "vendingenablemachine" => InteractionType.VENDINGENABLEMACHINE,
                "alert" => InteractionType.ALERT,
                "onewaygate" => InteractionType.ONEWAYGATE,
                "loveshuffler" => InteractionType.LOVESHUFFLER,
                "habbowheel" => InteractionType.HABBOWHEEL,
                "dice" => InteractionType.DICE,
                "bottle" => InteractionType.BOTTLE,
                "teleport" => InteractionType.TELEPORT,
                "teleportfloor" => InteractionType.ARROW,
                "rentals" => InteractionType.RENTALS,
                "pet" => InteractionType.PET,
                "pool" or "water" => InteractionType.POOL,
                "roller" => InteractionType.ROLLER,
                "fbgate" => InteractionType.FBGATE,
                "iceskates" => InteractionType.ICESKATES,
                "normalskates" => InteractionType.NORMSLASKATES,
                "lowpool" => InteractionType.LOWPOOL,
                "haloweenpool" => InteractionType.HALOWEENPOOL,
                "football" or "ball" => InteractionType.FOOTBALL,
                "footballgoalgreen" or "green_goal" => InteractionType.FOOTBALLGOALGREEN,
                "footballgoalyellow" or "yellow_goal" => InteractionType.FOOTBALLGOALYELLOW,
                "footballgoalred" or "red_goal" => InteractionType.FOOTBALLGOALRED,
                "footballgoalblue" or "blue_goal" => InteractionType.footballgoalblue,
                "footballcountergreen" => InteractionType.FOOTBALLCOUNTERGREEN,
                "footballcounteryellow" => InteractionType.FOOTBALLCOUNTERYELLOW,
                "footballcounterblue" => InteractionType.FOOTBALLCOUNTERBLUE,
                "footballcountered" => InteractionType.FOOTBALLCOUNTERRED,
                "banzaigateblue" or "bb_blue_gate" => InteractionType.BANZAIGATEBLUE,
                "banzaigatered" or "bb_red_gate" => InteractionType.BANZAIGATERED,
                "banzaigateyellow" or "bb_yellow_gate" => InteractionType.BANZAIGATEYELLOW,
                "banzaigategreen" or "bb_green_gate" => InteractionType.BANZAIGATEGREEN,
                "banzaifloor" or "bb_patch" => InteractionType.BANZAIFLOOR,
                "banzaiscoreblue" => InteractionType.BANZAISCOREBLUE,
                "banzaiscorered" => InteractionType.BANZAISCORERED,
                "banzaiscoreyellow" => InteractionType.BANZAISCOREYELLOW,
                "banzaiscoregreen" => InteractionType.BANZAISCOREGREEN,
                "banzaitele" or "bb_teleport" => InteractionType.BANZAITELE,
                "banzaipuck" => InteractionType.BANZAIPUCK,
                "banzaipyramid" => InteractionType.BANZAIPYRAMID,
                "wf_blob2" => InteractionType.BANZAIBLO,
                "wf_blob" => InteractionType.BANZAIBLOB,
                "freezetimer" or "banzaicounter" or "counter" => InteractionType.CHRONOTIMER,
                "freezeexit" => InteractionType.FREEZEEXIT,
                "freezeredcounter" => InteractionType.FREEZEREDCOUNTER,
                "freezebluecounter" => InteractionType.FREEZEBLUECOUNTER,
                "freezeyellowcounter" => InteractionType.FREEZEYELLOWCOUNTER,
                "freezegreencounter" => InteractionType.FREEZEGREENCOUNTER,
                "freezeyellowgate" => InteractionType.FREEZEYELLOWGATE,
                "freezeredgate" => InteractionType.FREEZEREDGATE,
                "freezegreengate" => InteractionType.FREEZEGREENGATE,
                "freezebluegate" => InteractionType.FREEZEBLUEGATE,
                "freezetileblock" => InteractionType.FREEZETILEBLOCK,
                "freezetile" => InteractionType.FREEZETILE,
                "jukebox" => InteractionType.JUKEBOX,
                "triggertimer" or "wf_trg_attime" => InteractionType.TRIGGER_ONCE,
                "wf_trg_collision" => InteractionType.TRIGGER_COLLISION,
                "triggerroomenter" or "wf_trg_enterroom" => InteractionType.TRIGGER_AVATAR_ENTERS_ROOM,
                "triggergameend" or "wf_trg_gameend" => InteractionType.TRIGGER_GAME_ENDS,
                "triggergamestart" or "wf_trg_gamestart" => InteractionType.TRIGGER_GAME_STARTS,
                "triggerrepeater" or "wf_trg_timer" => InteractionType.TRIGGER_PERIODICALLY,
                "wf_trg_period_long" => InteractionType.TRIGGER_PERIODICALLY_LONG,
                "triggeronusersay" or "wf_trg_onsay" => InteractionType.TRIGGER_AVATAR_SAYS_SOMETHING,
                "wf_trg_cmd" => InteractionType.TRIGGER_COMMAND,
                "wf_trg_cls_user" => InteractionType.TRIGGER_COLLISION_USER,
                "triggerscoreachieved" or "wf_trg_atscore" => InteractionType.TRIGGER_SCORE_ACHIEVED,
                "triggerstatechanged" or "wf_trg_furnistate" => InteractionType.TRIGGER_STATE_CHANGED,
                "triggerwalkonfurni" or "wf_trg_onfurni" => InteractionType.TRIGGER_WALK_ON_FURNI,
                "triggerwalkofffurni" or "wf_trg_offfurni" => InteractionType.TRIGGER_WALK_OFF_FURNI,
                "actiongivescore" or "wf_act_givepoints" => InteractionType.ACTION_GIVE_SCORE,
                "actionposreset" or "wf_act_matchfurni" => InteractionType.ACTION_POS_RESET,
                "actionmoverotate" or "wf_act_moverotate" => InteractionType.ACTION_MOVE_ROTATE,
                "actionresettimer" => InteractionType.ACTION_RESET_TIMER,
                "actionshowmessage" or "wf_act_saymsg" => InteractionType.ACTIONSHOWMESSAGE,
                "wf_act_give_reward" => InteractionType.ACTION_GIVE_REWARD,
                "superwired" => InteractionType.ACTION_SUPER_WIRED,
                "superwiredcondition" => InteractionType.CONDITION_SUPER_WIRED,
                "actionteleportto" or "wf_act_moveuser" => InteractionType.ACTION_TELEPORT_TO,
                "wf_act_endgame_team" => InteractionType.ACTION_ENDGAME_TEAM,
                "wf_act_call_stacks" => InteractionType.ACTION_CALL_STACKS,
                "actiontogglestate" or "wf_act_togglefurni" => InteractionType.ACTION_TOGGLE_STATE,
                "wf_act_kick_user" or "wf_act_kickuser" or "wf_act_kick" => InteractionType.ACTION_KICK_USER,
                "wf_act_flee" => InteractionType.ACTION_FLEE,
                "wf_act_chase" => InteractionType.ACTION_CHASE,
                "wf_act_collisioncase" => InteractionType.ACTION_COLLISION_CASE,
                "wf_act_collisionteam" => InteractionType.ACTION_COLLISION_TEAM,
                "wf_act_move_to_dir" => InteractionType.ACTION_MOVE_TO_DIR,
                "conditionfurnishaveusers" or "wf_cnd_furnis_hv_avtrs" => InteractionType.CONDITION_FURNIS_HAVE_USERS,
                "wf_cnd_furnis_hv_prsn" or "wf_cnd_not_hv_avtrs" => InteractionType.CONDITION_FURNIS_HAVE_NO_USERS,
                "conditionstatepos" => InteractionType.CONDITION_STATE_POS,
                "wf_cnd_stuff_is" => InteractionType.CONDITION_STUFF_IS,
                "wf_cnd_not_stuff_is" => InteractionType.CONDITION_NOT_STUFF_IS,
                "wf_cnd_not_match_snap" => InteractionType.CONDITION_STATE_POS_NEGATIVE,
                "conditiontimelessthan" => InteractionType.CONDITION_TIME_LESS_THAN,
                "conditiontimemorethan" => InteractionType.CONDITION_TIME_MORE_THAN,
                "conditiontriggeronfurni" or "wf_cnd_trggrer_on_frn" => InteractionType.CONDITION_TRIGGER_ON_FURNI,
                "wf_cnd_not_trggrer_on" => InteractionType.CONDITION_TRIGGER_ON_FURNI_NEGATIVE,
                "wf_cnd_has_furni_on" => InteractionType.CONDITION_HAS_FURNI_ON_FURNI,
                "wf_cnd_not_furni_on" => InteractionType.CONDITION_HAS_FURNI_ON_FURNI_NEGATIVE,
                "wf_cnd_date_rng_active" => InteractionType.CONDITION_DATE_RNG_ACTIVE,
                "ringplate" => InteractionType.RINGPLATE,
                "colortile" => InteractionType.COLORTILE,
                "colorwheel" => InteractionType.COLORWHEEL,
                "floorswitch1" or "floorswitch2" => InteractionType.FLOORSWITCH1,
                "firegate" => InteractionType.FIREGATE,
                "glassfoor" => InteractionType.GLASSFOOR,
                "specialrandom" or "wf_xtra_random" => InteractionType.SPECIALRANDOM,
                "specialunseen" or "wf_xtra_unseen" => InteractionType.SPECIALUNSEEN,
                "wire" => InteractionType.WIRE,
                "wireCenter" => InteractionType.WIRECENTER,
                "wireCorner" => InteractionType.WIRECORNER,
                "wireSplitter" => InteractionType.WIRESPLITTER,
                "wireStandard" => InteractionType.WIRESTANDARD,
                "puzzlebox" => InteractionType.PUZZLEBOX,
                "gift" => InteractionType.GIFT,
                "extrabox" => InteractionType.EXTRABOX,
                "deluxebox" => InteractionType.DELUXEBOX,
                "legendbox" => InteractionType.LEGENDBOX,
                "badgebox" => InteractionType.BADGEBOX,
                "lootbox2022" => InteractionType.LOOTBOX2022,
                "maniqui" => InteractionType.MANNEQUIN,
                "bgupdater" => InteractionType.TONER,
                "bot" => InteractionType.BOT,
                "adsbackground" => InteractionType.ADS_BACKGROUND,
                "badge_display" => InteractionType.BADGE_DISPLAY,
                "badge_troc" => InteractionType.BADGE_TROC,
                "tvyoutube" => InteractionType.TVYOUTUBE,
                "pilemagic" => InteractionType.PILEMAGIC,
                "jmphorse" => InteractionType.JMPHORSE,
                "groupfurni" => InteractionType.GUILD_ITEM,
                "groupgate" => InteractionType.GUILD_GATE,
                "floor" => InteractionType.FLOOR,
                "wallpaper" => InteractionType.WALLPAPER,
                "landscape" => InteractionType.LANDSCAPE,
                "wf_cnd_actor_in_group" => InteractionType.CONDITION_ACTOR_IN_GROUP,
                "wf_cnd_not_in_group" => InteractionType.CONDITION_NOT_IN_GROUP,
                "pressurepad" or "arrowplate" or "pressure_pad" => InteractionType.PRESSUREPAD,
                "gnomebox" => InteractionType.GNOMEBOX,
                "monstergraine" => InteractionType.MONSTERGRAINE,
                "highscore" => InteractionType.HIGHSCORE,
                "hightscorepoints" => InteractionType.HIGHSCOREPOINTS,
                "wf_trg_bot_reached_stf" => InteractionType.TRIGGER_BOT_REACHED_STF,
                "wf_trg_bot_reached_avtr" => InteractionType.TRIGGER_BOT_REACHED_AVTR,
                "wf_act_bot_clothes" => InteractionType.ACTION_BOT_CLOTHES,
                "wf_trg_trigger_self" => InteractionType.TRIGGER_SELF,
                "wf_act_bot_teleport" => InteractionType.ACTION_BOT_TELEPORT,
                "wf_act_bot_follow_avatar" => InteractionType.ACTION_BOT_FOLLOW_AVATAR,
                "wf_act_bot_give_handitem" => InteractionType.ACTION_BOT_GIVE_HANDITEM,
                "wf_act_bot_move" => InteractionType.ACTION_BOT_MOVE,
                "wf_act_user_move" => InteractionType.ACTION_USER_MOVE,
                "wf_act_bot_talk_to_avatar" => InteractionType.ACTION_BOT_TALK_TO_AVATAR,
                "wf_act_bot_talk" => InteractionType.ACTION_BOT_TALK,
                "wf_cnd_has_handitem" => InteractionType.CONDITION_HAS_HANDITEM,
                "wf_act_join_team" => InteractionType.ACTION_JOIN_TEAM,
                "wf_act_leave_team" => InteractionType.ACTION_LEAVE_TEAM,
                "wf_act_give_score_tm" => InteractionType.ACTION_GIVE_SCORE_TM,
                "wf_cnd_actor_in_team" => InteractionType.CONDITION_ACTOR_IN_TEAM,
                "wf_cnd_not_in_team" => InteractionType.CONDITION_NOT_IN_TEAM,
                "wf_cnd_not_user_count" => InteractionType.CONDITION_NOT_USER_COUNT,
                "wf_cnd_user_count_in" => InteractionType.CONDITION_USER_COUNT_IN,
                "crackable" => InteractionType.CRACKABLE,
                "lovelock" => InteractionType.LOVELOCK,
                "exchange" => InteractionType.EXCHANGE,
                "horse_saddle_1" => InteractionType.HORSE_SADDLE_1,
                "horse_saddle_2" => InteractionType.HORSE_SADDLE_2,
                "horse_hairstyle" => InteractionType.HORSE_HAIRSTYLE,
                "horse_body_dye" => InteractionType.HORSE_BODY_DYE,
                "horse_hair_dye" => InteractionType.HORSE_HAIR_DYE,
                "badge" => InteractionType.BADGE,
                "trampoline" => InteractionType.TRAMPOLINE,
                "treadmill" => InteractionType.TREADMILL,
                "crosstrainer" => InteractionType.CROSSTRAINER,
                _ => InteractionType.NONE,
            };
        }
    }
}
