namespace WibboEmulator.Games.Items;

public enum ItemCategoryType
{
    DEFAULT = 1,
    WALL_PAPER,
    FLOOR,
    LANDSCAPE,
    POST_IT,
    POSTER,
    SOUND_SET,
    TRAX_SONG,
    PRESENT,
    ECOTRON_BOX,
    TROPHY,
    CREDIT_FURNI,
    PET_SHAMPOO,
    PET_CUSTOM_PART,
    PET_CUSTOM_PART_SHAMPOO,
    PET_SADDLE,
    GUILD_FURNI,
    GAME_FURNI,
    MONSTERPLANT_SEED,
    MONSTERPLANT_REVIVAL,
    MONSTERPLANT_REBREED,
    MONSTERPLANT_FERTILIZE,
    FIGURE_PURCHASABLE_SET
}